package main

import (
	"santrinet-api/database"
	"santrinet-api/routes"
	"time"

	"github.com/gin-contrib/cors"

	"github.com/gin-gonic/gin"

	_ "santrinet-api/docs" // import docs generated by swag

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title       Edulite API
// @version     1.0
// @description API untuk sistem Edulite
// @host        localhost:5555
// @BasePath    /
// @schemes     http
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	r := gin.Default()
	database.InitDB()
	r.Use(cors.New(cors.Config{
		AllowOrigins: []string{
			"http://192.168.100.99:10000",
			"https://simsmk.sch.id",
		}, // Ganti dengan domain tertentu jika perlu
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Authorization", "Content-Type"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))

	r.OPTIONS("/*path", func(c *gin.Context) {
		c.Status(204)
	})

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Auth
	routes.AuthRoutes(r)
	routes.SantriRoutes(r)
	routes.KamarSantriRoutes(r)
	routes.PelanggaranRoutes(r)
	routes.RekamMedisRoutes(r)
	routes.PresensiSantriRoutes(r)
	routes.PengajuanPelanggaranRoutes(r)
	routes.TatibRoutes(r)
	routes.LoginRoutes(r)

	r.Run(":5555")
}
